// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recrutech_api.Model;

#nullable disable

namespace Recrutech_api.Migrations
{
    [DbContext(typeof(recrutechDbContext))]
    [Migration("20240326014034_updateDB")]
    partial class updateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CurriculumVacancy", b =>
                {
                    b.Property<int>("CvsId")
                        .HasColumnType("integer");

                    b.Property<int>("VacanciesId")
                        .HasColumnType("integer");

                    b.HasKey("CvsId", "VacanciesId");

                    b.HasIndex("VacanciesId");

                    b.ToTable("CurriculumVacancy");
                });

            modelBuilder.Entity("Recrutech_api.Model.Curriculum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Cvs");
                });

            modelBuilder.Entity("Recrutech_api.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("CurriculumId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsRecruiter")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string[]>("Tecnologies")
                        .HasColumnType("text[]");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Recrutech_api.Model.Vacancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string[]>("Benefits")
                        .HasColumnType("text[]");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("Contract")
                        .HasColumnType("integer");

                    b.Property<string>("Enterprise")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Remuneration")
                        .HasColumnType("text");

                    b.Property<string[]>("Requirements")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Vacancies");
                });

            modelBuilder.Entity("UserVacancy", b =>
                {
                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.Property<int>("VacanciesId")
                        .HasColumnType("integer");

                    b.HasKey("UsersId", "VacanciesId");

                    b.HasIndex("VacanciesId");

                    b.ToTable("UserVacancy");
                });

            modelBuilder.Entity("CurriculumVacancy", b =>
                {
                    b.HasOne("Recrutech_api.Model.Curriculum", null)
                        .WithMany()
                        .HasForeignKey("CvsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recrutech_api.Model.Vacancy", null)
                        .WithMany()
                        .HasForeignKey("VacanciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recrutech_api.Model.Curriculum", b =>
                {
                    b.HasOne("Recrutech_api.Model.User", "User")
                        .WithOne("Curriculum")
                        .HasForeignKey("Recrutech_api.Model.Curriculum", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserVacancy", b =>
                {
                    b.HasOne("Recrutech_api.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recrutech_api.Model.Vacancy", null)
                        .WithMany()
                        .HasForeignKey("VacanciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recrutech_api.Model.User", b =>
                {
                    b.Navigation("Curriculum");
                });
#pragma warning restore 612, 618
        }
    }
}
